Tim feature pars usfm
texttree/community-check-app pull request #16
Opened 2023-11-22 07:41 UTC by Vorobushec

Парсинг usfm файла, просмотр глав, сохранение и скачивание заметок

2023-11-22 08:37 UTC, foxprogs commented on components/CheckList.js
> +                  <td className="border p-2 text-center">{index + 1}</td>
я думаю эту колонку можно вообще убрать. Смысла от нее нет. @Valyukhov что думаешь?

2023-11-22 08:40 UTC, foxprogs commented on public/copy.svg
а почему иконки не берешь с heroicons? Плюсы в том что все иконки тогда будут в одном стиле (стрелки, скопировать, скачать я бы тоже сделал иконкой) а второе - там иконки в две строчки, а тут не оптимизированные получаются.

2023-11-22 08:42 UTC, foxprogs commented on supabase/migrations/20231003080113_fix_functions.sql
> +CREATE OR REPLACE FUNCTION public.check_user_books(project_id int8)
может тут вернуть на bigint как и раньше было? По идее не в этом была проблема в прошлый раз.

2023-11-22 08:45 UTC, foxprogs commented on helpers/downloadNotes.js
> +      const { chapter, verse, note } = not
одна заметка - `note`, не `not`

2023-11-22 08:58 UTC, foxprogs commented on helpers/downloadNotes.js
> +    link.download = `${check.name}.tsv`
может в имя файла дописать время когда он скачал, типа `${check.name}_${(new Date()).toISOString()}.tsv`

2023-11-22 08:59 UTC, foxprogs commented on helpers/downloadNotes.js
> +    console.error('Ошибка при загрузке заметок:', error)
текст надо локализовать

2023-11-22 09:07 UTC, foxprogs commented on pages/api/checks/[checkId]/index.js
> +          .upsert([postData])
мне не нравится этот апсерт. Вообще надо сделать чтобы через функцию он добавлял а в рлс надо отключить возможность добавлять в базу. У одной проверки у нас существует один материал. Связь один к одному. А этот апсерт получается позволяет добавить два материала к проверке или вообще добавить материал к другой. 
1 вариант - добавить в таблицу параметр что check_id должен быть уникальным.
2 вариант - запертить вставку, только редактирование. Добавить триггер, как только создали проверку сразу к ней создать пустой материал. Если смотреть на викану, мне кажется там так же устроен бриф. Как только создал ты проект - к нему триггером создается бриф и больше их создавать нельзя. Что думаешь @Valyukhov ?
Если не успеешь сейчас исправить - добавь ишью.

2023-11-22 09:44 UTC, foxprogs commented on pages/api/checks/[checkId]/notes/index.js
> +          .eq(' material_id', material.id)
создай ишью, это надо одним запросом сделать а не двумя

2023-11-22 09:45 UTC, foxprogs commented on pages/api/checks/[checkId]/notes/index.js
> +        else console.log(data)
это надо убрать

2023-11-22 09:45 UTC, foxprogs commented on pages/api/checks/[checkId]/notes/index.js
> +        return res.status(404).json({ error: 123 })
тут тоже ошибку надо по другому написать

2023-11-22 09:54 UTC, foxprogs commented on pages/api/projects/[projectId]/books/[bookId]/checks/[checkId]/index.js
> +              material_link,
тут правильная логика что ты материал обновляешь? Надо же быть точно уверенным что ты его загрузил а не просто ссылку поменял? Я бы может перенес обновление ссылки в то место, где ты контент загружаешь в таблицу материалов. 
@Valyukhov что думаешь?
Может быть даже перенести это поле в таблицу материалов?

2023-11-22 10:45 UTC, foxprogs commented on pages/projects/[projectId]/[bookId]/index.js
> +  const { mutate } = useSWRConfig()
а почему так? Вроде же useSWR() возвращает mutate

2023-11-22 10:47 UTC, foxprogs commented on pages/projects/[projectId]/[bookId]/index.js
> +          mutate(key, data, options)
а что за параметры ты тут передаешь? Это же не будет работать

2023-11-22 10:49 UTC, foxprogs commented on pages/checks/[checkId]/index.js
> +  const [testNotes, setTestNotes] = useState('')
а что такое testNotes? Почему такое имя?

2023-11-22 10:51 UTC, foxprogs commented on pages/checks/[checkId]/index.js
> +  const PreviousChapter = () => {
с большой буквы только компоненты

2023-11-22 10:52 UTC, foxprogs commented on pages/checks/[checkId]/index.js
> +    const note = testNotes
а для чего вот это написано?

2023-11-22 10:53 UTC, foxprogs commented on pages/checks/[checkId]/index.js
> +    const deleted_at = material.deleted_at
а это что? По идее ты не должен показывать материал если указано что он удален

2023-11-22 10:54 UTC, foxprogs commented on pages/checks/[checkId]/index.js
> +          console.log('uploadTrue')
надо какой-то нормальный вывод успеха

2023-11-22 11:11 UTC, foxprogs commented on pages/checks/[checkId]/index.js
> +    const note = testNotes
заметка равно тестовые заметки. Непонятно

2023-11-22 12:02 UTC, foxprogs commented on pages/projects/[projectId]/[bookId]/[checkId].js
> +  const chechPageRef = useRef(null)
наверное тут опечатка chech

2023-11-22 12:06 UTC, foxprogs commented on pages/projects/[projectId]/[bookId]/[checkId].js
> +  const { data: checks, err } = useSWR(
err там нет, он возвращает error

2023-11-22 12:27 UTC, foxprogs commented on pages/projects/[projectId]/[bookId]/[checkId].js
> +        console.error('Unable to copy text', err)
тебе бы какую-то либу подключить для уведомлений чтобы не в консоль выдавать. Ну и перевод тут нужен. Перевод сейчас добавь а про toast библиотеку - в ишью

2023-11-22 12:29 UTC, foxprogs commented on pages/projects/[projectId]/[bookId]/[checkId].js
> +  const { data: checks, err } = useSWR(
а для чего тебе вообще все проверки? Ты же на странице одной конкретной

2023-11-22 12:30 UTC, foxprogs commented on pages/projects/[projectId]/[bookId]/[checkId].js
> +      checks.map((el) => {
для чего тут этот перебор проверок если с базы можно сразу одну получить

2023-11-22 12:35 UTC, foxprogs commented on pages/projects/[projectId]/[bookId]/[checkId].js
> +              .then((materialId) => {})
а это что означает?

2023-11-22 12:35 UTC, foxprogs commented on pages/projects/[projectId]/[bookId]/[checkId].js
> +            setErrorMessage('Введите правильную ссылку на ресурс')
перевод

2023-11-22 12:36 UTC, foxprogs commented on pages/projects/[projectId]/[bookId]/[checkId].js
> +        return materialId
почему не сделать сразу return res.data.id

2023-11-22 12:46 UTC, foxprogs commented on pages/api/projects/[projectId]/books/[bookId]/checks/[checkId]/material/index.js
все замечания по этому коду я написал в другом файле, где почему-то был копипаст этого кода

2023-11-22 12:46 UTC, foxprogs requested changes
нужно исправить некоторые замечания

2023-11-23 09:24 UTC, Valyukhov commented on components/CheckList.js
> +                  <td className="border p-2 text-center">{index + 1}</td>
поддерживаю

2023-11-23 09:25 UTC, Valyukhov commented on components/CheckList.js
> +                        onClick={() => {
onClick={() =>  downloadNotes(check)}

2023-11-23 09:30 UTC, Valyukhov commented on components/CheckList.js
> +              {checks.map((check, index) => (
тут точно по умлочанию useSWR сначала возвращает массив?
`{checks.map`
возможно ошибка будет если сначала undefined.

2023-11-23 09:45 UTC, Valyukhov commented on helpers/usfmHelper.js
> +    return { verse: el[0], text: getVerseText(el[1].verseObjects, false) }
Не знаю, будут ли через этот сервис проверять usfm уже ближе к финальным текстам, после добавления привязки к источнику а также дополнительных тегов. @Vorobushec ты заливаешь эти версии и наверное лучше знаешь.
Но если все-таки будут, то в Vcana добавили поддержку некоторых тегов.
- https://github.com/texttree/v-cana/blob/master/utils/usfmHelper.js
А в этом варианте - отключены любые непонятные теги
`return { verse: el[0], text: getVerseText(el[1].verseObjects, **false**) }`

2023-11-23 09:47 UTC, Valyukhov commented on pages/api/projects/[projectId]/books/[bookId]/checks/[checkId]/index.js
> +              material_link,
да, согласен, чтобы всё было в материалах

2023-11-23 09:49 UTC, Valyukhov commented on components/CheckList.js
> +import React, { useState } from 'react'
React разве нужен в Next? В Vcana не импортируем
`import React`

2023-11-23 10:16 UTC, Valyukhov commented on pages/projects/[projectId]/[bookId]/[checkId].js
> +import React, { useState, useEffect, useRef } from 'react'
React убрать

2023-11-23 10:21 UTC, Valyukhov commented on pages/projects/[projectId]/[bookId]/[checkId].js
> +              })
а зачем тут return
.then(() => upsertMaterial(jsonData))
так проверь - сработает?

2023-11-23 10:26 UTC, Valyukhov commented on pages/checks/[checkId]/index.js
> +  const [arrayLenght, setArrayLenght] = useState('')
arrayLength
setArrayLength
not _lenght_ but **length**

2023-11-23 10:30 UTC, Valyukhov commented on pages/checks/[checkId]/index.js
> +            {chapter.map((verse, index) => (
`const [chapter, setChapter] = useState('') `
у тебя по умолчанию текст, а тут используешь как массив
`chapter.map`

2023-11-23 10:32 UTC, Valyukhov commented on pages/checks/[checkId]/index.js
> +        {chapter && (
const [chapter, setChapter] = useState('')  - если тут поставишь массив по-умолчанию, тогда возможно надо  будет проверять ещё и `chapter && chapter.length &&(`

2023-11-23 10:37 UTC, Valyukhov reviewed
Есть замечания

2024-02-26 06:48 UTC, foxprogs commented on helpers/downloadNotes.js
> +    const notes = await responseMaterials.json()
у тебя же axios есть, почему через fetch делаешь?

2024-02-26 08:09 UTC, foxprogs commented on pages/api/checks/[checkId]/index.js
> +    // }
try catch надо вернуть, мы убирали чтобы найти точно код ошибки

2024-02-26 11:38 UTC, foxprogs commented on public/locales/en/common.json
примени на файле сортировку json

2024-02-26 11:54 UTC, foxprogs commented on pages/projects/[projectId]/[bookId]/index.js
> +    const name = 'Name Check'
а это дефолтное имя? Надо убрать, или хотя бы перевод тогда поставить. Но лучше сделать как-то по другому, чтобы пользователь понял что это его новая проверка

2024-02-26 12:00 UTC, foxprogs commented on pages/projects/[projectId]/[bookId]/[checkId].js
> +        >
а для чего тег form тут?

2024-02-29 07:51 UTC, DenisArger approved these changes

2024-02-29 18:34 UTC, merged