Fix getting notes for checking in one request denis arger 19
texttree/community-check-app pull request #33
Opened 2024-03-18 14:59 UTC by DenisArger

It is implemented to receive notes for verification with a single sql query. Fixed the creation of notes. #19

2024-03-18 19:07 UTC, foxprogs commented on pages/api/checks/[checkId]/notes/index.js
> +        const { data, error } = await supabase.rpc('insert_note', {
надо тогда убрать supabaseService из импорта

2024-03-18 19:08 UTC, foxprogs commented on pages/api/checks/[checkId]/notes/index.js
>            inspector_id: null,
если это персональная заметка то тут же будет не null. Надо будет проверить и убедиться что такой проверяющий есть, и записать его айди

2024-03-18 19:11 UTC, foxprogs commented on pages/api/checks/[checkId]/notes/index.js
> +        const { data, error } = await supabase.rpc('insert_note', {
а, вроде не так. Тут как раз надо сервисный сапабэйз же использовать. У пользователя нет логина и пароля по этому серверный апи выдаст что такого пользователя нет. 
Не авторизованный юзер тут пишет свою заметку в базу. По этому мы тут проверяем не авторизацию а проверяем айди проверки, что она существует. И если это пишет пользователь со страницы персональной проверки, то надо и его айди тоже проверить.

2024-03-18 19:15 UTC, foxprogs commented on pages/api/checks/[checkId]/notes/index.js
>      case 'GET': // получить заметки
запрос на получение заметок у нас работает в двух случаях. 1 - это выгрузка заметок создателем проверки. Тут надо взять просто все заметки и отдать их в нужном формате. Сейчас тут только тсв, но надо в параметрах запроса принимать формат, тсв или жсон. И это у нас авторизованный пользователь. Значит доступ или по токену или по логин-пароль.
Второй вариант - это вернуть заметки персонального проверяющего. У него есть персональная ссылка, когда он открывает - там чуть другой формат, там кроме текста еще надо показать все заметки которые он уже писал. По этому тут придет айди проверки и айди проверяющего и надо его заметки отдать. 
Так же учитываем время, то есть если проверка уже закончилась, ничего не отдавать.

2024-03-18 19:16 UTC, foxprogs commented on pages/api/checks/[checkId]/notes/index.js
>      case 'GET': // получить заметки
Возможно лучше эти два гет запроса разделить, пусть будет разный юрл

2024-03-18 19:18 UTC, foxprogs requested changes
надо исправить пару методов

2024-03-25 18:11 UTC, DenisArger commented on pages/api/checks/[checkId]/notes/index.js
> +        const { data, error } = await supabase.rpc('insert_note', {
перенес  в ишью

2024-03-25 18:11 UTC, DenisArger commented on pages/api/checks/[checkId]/notes/index.js
>            inspector_id: null,
перенес в ишью

2024-03-25 18:13 UTC, DenisArger commented on pages/api/checks/[checkId]/notes/index.js
>      case 'GET': // получить заметки
Перенес в отдельное ишью

2024-03-26 10:13 UTC, merged