Feature acces token denis arger 16
texttree/community-check-app pull request #60
Opened 2024-04-05 16:18 UTC by DenisArger

The token generation page has been rewritten.

2024-04-08 08:11 UTC, Valyukhov commented on pages/tokens.js
> +                <th className="px-4 py-2 border border-gray-300">{t('')}</th>
а для чего тут использовать функцию `t`?

2024-04-08 08:48 UTC, Valyukhov reviewed
1 замечание

2024-04-08 08:49 UTC, Valyukhov approved these changes

2024-04-08 08:53 UTC, foxprogs commented on pages/tokens.js
> +      toast.error('Failed to generate or store tokens')
переводы для всех toast

2024-04-08 09:16 UTC, Valyukhov commented
![image](https://github.com/texttree/community-check-app/assets/74174349/5c2429be-2e9d-4a75-a638-2c1b529bb9f1)
@DenisArger 
когда ставлю пробел после названия - сохраняет все-равно

2024-04-08 09:18 UTC, foxprogs commented on pages/tokens.js
> +              {tokens.map((token) => {
получается что функция возвращает полностью токены и ты только на стороне клиента скрываешь его? Если да то это не гуд. Если получить доступ к аккаунту то можно легко получить все токены. Тут нужно сделать так, чтобы никто не смог их получить. Например так:
1. В базе таблица с токенами, у которой отключены RLS чтобы никто не мог получить из таблицы данные. 
2. Работа с этой таблицей ведется через апи некста, в котором ты используешь сервисный ключ. 
3. Прежде чем делать запросы, надо всегда проверять что юзер аутентифицирован.
4. При создании токена можно как и сейчас возвращать его.
5. При получении токенов надо на стороне апи получить список и скрыть их, оставив только по 4 символа.

2024-04-08 09:43 UTC, foxprogs commented on supabase/migrations/20240408100248_update_tokens.sql
> +$$ LANGUAGE plpgsql;
надо сделать так чтобы эту функцию нельзя было вызвать на стороне клиента

2024-04-08 09:51 UTC, foxprogs requested changes
надо подправить получение и отображение токенов

2024-04-08 09:53 UTC, foxprogs commented on supabase/migrations/20240408100248_update_tokens.sql
> +    DELETE FROM public.tokens WHERE id = token_id;
тут ты передаешь этот самый токен? Я думаю надо тогда добавить еще ключ, по которому будешь удалять. Не гуд просто их в итоге в открытую передавать. Тогда теряется смысл того что ты его показываешь только при создании и скрываешь

2024-04-09 07:51 UTC, foxprogs commented on supabase/migrations/20240408100248_update_tokens.sql
> +    VALUES (auth.uid(), LOWER(TRIM(p_name)))
ты же исправил код прям в миграции. По этому она не выполнится на проде. Он же уже применял эту имграцию раньше.

2024-04-09 07:54 UTC, foxprogs commented on pages/tokens.js
> +      toast.success('Token deleted successfully!')
перевод

2024-04-12 08:33 UTC, foxprogs commented on supabase/migrations/20240410233012_update_tokens.sql
> +END;
надо добавить првоерку user id а то удаляет токены всех подряд)

2024-04-12 08:37 UTC, foxprogs commented on supabase/migrations/20240408100248_update_tokens.sql
> +    VALUES (auth.uid(), LOWER(TRIM(p_name)))
LOWER я бы тут убрал. Просто ты напишешь к примеру имя "TextTree" или "Bible John"  а с базы в итоге будет отображаться в нижнем регистре все. А то что ты в сравнении приводишь к нижнему регистру - это гуд

2024-04-12 19:10 UTC, merged